"""initial schema

Revision ID: 769d8fceba1d
Revises: 
Create Date: 2026-07-19 22:30:58.692675

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '769d8fceba1d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('cue', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('active', 'graduated', 'archived', name='habitstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weeks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_day', sa.Date(), nullable=False),
    sa.Column('pool_cents', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('start_day')
    )
    op.create_table('checkoffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('habit_id', 'day', name='uq_checkoff_habit_day')
    )
    op.create_table('habit_weeks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_id', sa.Integer(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('share_permille', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ),
    sa.ForeignKeyConstraint(['week_id'], ['weeks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_id', 'habit_id', name='uq_habitweek')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('habit_weeks')
    op.drop_table('checkoffs')
    op.drop_table('weeks')
    op.drop_table('habits')
    # create_table made the enum type on Postgres, but drop_table won't remove it
    sa.Enum(name='habitstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
